#!/bin/bash
set -euo pipefail

BOOK_ASSISTANT=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
source "$BOOK_ASSISTANT/.venv/bin/activate"
python "$BOOK_ASSISTANT/src/book_assistant/Qwen3CloneVoice.py" "$@"
deactivate